export const GLOBAL_CONFIG = {
  SITE_PATH: 'https://lokmat-tv-final.vercel.app',
  SITE_NAVIGATION: {
    name: [
      'होम',
      'महाराष्ट्र',
      'ताज्या ',
      'शहरं',
      'अहिल्यानगर',
      'अकोला',
      'अमरावती',
      'छत्रपती संभाजीनगर',
      'बीड',
      'भंडारा',
      'बुलढाणा',
      'चंद्रपूर',
      'धुळे',
      'गडचिरोली',
      'गोवा',
      'गोंदिया',
      'हिंगोली',
      'जालना',
      'जळगाव',
      'कोल्हापूर',
      'लातूर',
      'मालेगाव',
      'मुंबई',
      'नागपूर',
      'नांदेड',
      'नंदुरबार',
      'नाशिक',
      'नवी मुंबई',
      'पंढरपूर',
      'परभणी',
      'पिंपरी-चिंचवड',
      'पुणे',
      'रायगड',
      'रत्नागिरी',
      'सांगली',
      'सातारा',
      'सिंधुदुर्ग',
      'सोलापूर',
      'ठाणे',
      'धाराशिव',
      'वर्धा',
      'वसई विरार',
      'वाशिम',
      'यवतमाळ',
      'खामगाव',
      'भुसावळ',
      'पालघर',
      'राष्ट्रीय',
      'राजकारण',
      'फोटोफ्लिक',
      'व्हिडीओ',
      'संपादकीय ',
      'क्राइम',
      'क्रिकेट',
      'सखी',
      'भक्ती',
      'Lokmat Money',
      'आंतरराष्ट्रीय',
      'व्हायरल',
      'राशी भविष्य',
      'हेल्थ',
      'फूड',
      'क्रीडा',
      'तंत्रज्ञान',
      'बॉलीवुड',
      'मराठी सिनेमा',
      'टेलीविजन',
      'वेब सीरिज',
      'मुव्हीज',
      'म्युझिक',
      'Reviews',
      'फॅक्ट चेक',
      'युवा नेक्स्ट',
      'ब्लॉग्स',
      'फॅशन',
      'ब्यूटी',
      'लाइफ स्टाइल',
      'रिलेशनशिप',
      'शिक्षण',
      'गणेश महोत्सव',
      'जरा हटके',
      'ऑक्सिजन',
      'करिअर',
      'ट्रॅव्हल',
      'IPL',
      'इपेपर',
    ],
    url: [
      '/',
      'https://www.lokmat.com/maharashtra/',
      'https://www.lokmat.com/latestnews/',
      'https://www.lokmat.com/city/',
      'https://www.lokmat.com/ahilyanagar/',
      'https://www.lokmat.com/akola/',
      'https://www.lokmat.com/amravati/',
      'https://www.lokmat.com/chhatrapati-sambhajinagar/',
      'https://www.lokmat.com/beed/',
      'https://www.lokmat.com/bhandara/',
      'https://www.lokmat.com/buldhana/',
      'https://www.lokmat.com/chandrapur/',
      'https://www.lokmat.com/dhule/',
      'https://www.lokmat.com/gadchiroli/',
      'https://www.lokmat.com/goa/',
      'https://www.lokmat.com/gondia/',
      'https://www.lokmat.com/hingoli/',
      'https://www.lokmat.com/jalana/',
      'https://www.lokmat.com/jalgaon/',
      'https://www.lokmat.com/kolhapur/',
      'https://www.lokmat.com/latur/',
      'https://www.lokmat.com/malegaon/',
      'https://www.lokmat.com/mumbai/',
      'https://www.lokmat.com/nagpur/',
      'https://www.lokmat.com/nanded/',
      'https://www.lokmat.com/nandurbar/',
      'https://www.lokmat.com/nashik/',
      'https://www.lokmat.com/navi-mumbai/',
      'https://www.lokmat.com/pandharpur/',
      'https://www.lokmat.com/parabhani/',
      'https://www.lokmat.com/pimpri-chinchwad/',
      'https://www.lokmat.com/pune/',
      'https://www.lokmat.com/raigad/',
      'https://www.lokmat.com/ratnagiri/',
      'https://www.lokmat.com/sangli/',
      'https://www.lokmat.com/satara/',
      'https://www.lokmat.com/sindhudurga/',
      'https://www.lokmat.com/solapur/',
      'https://www.lokmat.com/thane/',
      'https://www.lokmat.com/dharashiv/',
      'https://www.lokmat.com/vardha/',
      'https://www.lokmat.com/vasai-virar/',
      'https://www.lokmat.com/vashim/',
      'https://www.lokmat.com/yavatmal/',
      'https://www.lokmat.com/topics/khamgaon/',
      'https://www.lokmat.com/topics/bhusawal/',
      'https://www.lokmat.com/topics/palghar/',
      'https://www.lokmat.com/national/',
      'https://www.lokmat.com/politics/',
      'https://www.lokmat.com/photos/',
      'https://www.lokmat.com/videos/',
      'https://www.lokmat.com/editorial/',
      'https://www.lokmat.com/crime/',
      'https://www.lokmat.com/cricket/',
      'https://www.lokmat.com/sakhi/',
      'https://www.lokmat.com/bhakti/',
      'http://www.lokmatmoney.com/',
      'https://www.lokmat.com/international/',
      'https://www.lokmat.com/social-viral/',
      'https://www.lokmat.com/astro/',
      'https://www.lokmat.com/health/',
      'https://www.lokmat.com/food/',
      'https://www.lokmat.com/sports/',
      'https://www.lokmat.com/tech/',
      'https://www.lokmat.com/bollywood/',
      'https://www.lokmat.com/marathi-cinema/',
      'https://www.lokmat.com/television/',
      'https://www.lokmat.com/web-series/',
      'https://www.lokmat.com/movies/',
      'https://www.lokmat.com/music/',
      'https://www.lokmat.com/reviews/',
      'https://www.lokmat.com/fact-check/',
      'https://www.lokmat.com/yuvanext/',
      'https://www.lokmat.com/blog/',
      'https://www.lokmat.com/fashion/',
      'https://www.lokmat.com/beauty/',
      'https://www.lokmat.com/lifestyle/',
      'https://www.lokmat.com/relationship/',
      'https://www.lokmat.com/eduction/',
      'https://www.lokmat.com/ganesh-mahotsav/',
      'https://www.lokmat.com/jarahatke/',
      'https://www.lokmat.com/oxygen/',
      'https://www.lokmat.com/career/',
      'https://www.lokmat.com/travel/',
      'https://www.lokmat.com/cricket/series/indian-premier-league-2023/2814/',
      'http://epaper.lokmat.com/',
    ],
  },
};
