import { Geist, Geist_Mono } from 'next/font/google';
// import './globals.css';
import './custom.css';

import Navbar from './components/Navbar';
import Head from 'next/head';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* CSS */}
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        /> */}
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212]  text-amber-400`}
      >
        <Navbar />
        <main className="  mt-[92px] md:mt-[140px] ">{children}</main>

        {/* jQuery (must load BEFORE Owl Carousel) */}
        {/* <Script src="https://code.jquery.com/jquery-3.6.0.min.js" strategy="beforeInteractive" /> */}

        {/* Owl Carousel (must load AFTER jQuery) */}
        {/* <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
          strategy="afterInteractive"
        /> */}

        <Script
          src="https://d3pc1xvrcw35tl.cloudfront.net/assets/js/jquery.min-v0.3.js"
          strategy="beforeInteractive"
        />

        <Script
          src="https://d3pc1xvrcw35tl.cloudfront.net/assets/js/owl.carousel-min-v0.2.js"
          strategy="afterInteractive"
        />
        <Script src="/owl-init.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
